apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: obsidian-search
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
    spec:
      containerConcurrency: 80
      containers:
        startupProbe:
          httpGet:
            httpHeaders:
              - name: Authorization
                value: Bearer local
            path: /health
          initialDelaySeconds: 30
          successThreshold: 1
          periodSeconds: 30
          timeoutSeconds: 30
          failureThreshold: 30
        image: gcr.io/obsidian-ai/obsidian-search:0.5.3
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets_firebase/svc.prod.json
          - name: SENTRY_RELEASE
            value: "0.5.3"
          - name: ENVIRONMENT
            value: "production"
          - name: UPLOAD_BATCH_SIZE
            value: "100"
          - name: MAX_NOTE_LENGTH
            value: "2000"
        ports:
          - containerPort: 8080
            name: http1
        resources:
          limits:
            cpu: "4"
            memory: 2048Mi
        volumeMounts:
          - name: settings
            readOnly: true
            mountPath: /secrets
          - name: firebase_admin_service_account
            mountPath: /secrets_firebase
            readOnly: true
      volumes:
        - name: settings
          secret:
            secretName: OBSIDIAN_SEARCH
            items:
              - key: "4"
                path: config.yaml
        - name: firebase_admin_service_account
          secret:
            secretName: FIREBASE_ADMIN_SERVICE_ACCOUNT
            items:
              - key: "1"
                path: svc.prod.json
      timeoutSeconds: 240
