FROM ghcr.io/another-ai/embedbase:latest
COPY ./middlewares/processing_time/processing_time.py /app/middlewares/processing_time/processing_time.py
COPY ./middlewares/enrich/enrich.py /app/middlewares/enrich/enrich.py