CREATE TABLE plan_usages (
  id SERIAL PRIMARY KEY,
  plan_id TEXT NOT NULL,
  user_id UUID NOT NULL,
  usage INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
