name: Deploy Function
# when supabase/functions/* is pushed to main
on:
  push:
    branches:
      - main
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase functions deploy consumeApi --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID
      - run: supabase functions deploy sendgrid --no-verify-jwt --project-ref $SUPABASE_PROJECT_ID